# Generated by Django 4.1.7 on 2023-03-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_information',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Additional_Information', to='Products.products'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Images', to='Products.products'),
        ),
    ]
