# Generated by Django 4.1.7 on 2023-03-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_additional_information_product_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='app_Products',
        ),
    ]
